apiVersion: v1
kind: Service
metadata:
  name: node-js-service
spec:
  type: ClusterIP
  selector:
    app: node-js
  ports:
  - port: 4000
    targetPort: 4000


# # WORKS
# apiVersion: v1
# kind: Service
# metadata:
#   name: node-js-service
# spec:
#   type: NodePort
#   selector:
#     app: node-js
#   ports:
#   - port: 4000
#     targetPort: 4000
