on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Build project
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 mv s3://${{ secrets.BUCKET_NAME }}/builds/previous s3://${{ secrets.BUCKET_NAME }}/backups/$(date +%Y-%m-%d) --recursive || true
          aws s3 mv s3://${{ secrets.BUCKET_NAME }}/builds/current s3://${{ secrets.BUCKET_NAME }}/builds/previous --recursive || true
          aws s3 cp client/build s3://${{ secrets.BUCKET_NAME }}/builds/current --recursive
